### ISSUE TITLE
"Researchers develop software"?

### ISSUE THREAD

**Issue by npch** [research-software/resosuma-data#1]
There's no explicit relation that is:

- researchers develop software

I know that:

- researchers are research software engineers
- research software engineers are researchers
- research software engineers develop software

but I'd argue that there are researchers who are not research software engineers who develop software. Or am I misunderstanding the directed graph?

**Comment by sdruskat** [comment]
Thanks Neil!

I'd argue that this would indeed be covered by the Researchers > are > RSEs > develop > Research Software path. I interpret RSE and Researcher as roles that can be taken on by the same people. Also, I'd argue that by the "soft" definition of RSE via rse.ac.uk, all Researchers that develop research software are RSEs. Perhaps we need to make this more obvious in the paper, i.e., have proper definitions for all roles.

Happy to hear your and other people's points of view on the RSE role, as I can see an argument that the soft definition may not hold under circumstances that aren't onboarding to the community. And perhaps resosuma should represent reality rather than ideals.

Also happy to see that the discussion about this has started :).

**Comment by npch** [comment]
I think my argument is that a person taking on the role of a researcher but not the role of an RSE develop software and that the soft definition is incorrect for this specific subset - they may be developing software, but they are not RSEs because they are not applying software engineering practices (either explicitly or unknowingly). 

Of course, there's a spectrum between this group and the group of researchers who develop software and apply software engineering practices who do not consider themselves RSEs but share the characteristics of an RSE.

**Comment by sdruskat** [comment]
Sorry for the delay in replying, on holidays just now.

I've thought about this and I agree, this should be included in the data model as it represents the state of affairs.

Would you like to write a wee pull request?
Thanks!

**Comment by sdruskat** [comment]
PR #2 merged.
